# Generated by Django 4.2.2 on 2023-06-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('contactNumber', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
